{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    vim
    wget
    kitty
    git
    google-chrome
    fastfetch
    wofi
    pavucontrol
    oh-my-zsh
    alacritty
    hyprpaper
    nil
    thefuck
    meslo-lgs-nf
    flameshot
    btop
    hyprshot
    apple-cursor
    xorg.xeyes
    waybar
    networkmanagerapplet
    pamixer
    vesktop
    slack
    nixpkgs-fmt
    nixd
    nixfmt-rfc-style
    zsh-powerlevel10k
    cmatrix
    obsidian
    eza
    bruno
    devenv
    redis
    texlive.combined.scheme-full
    anki-bin
    spotify
    nix-ld
    v4l-utils
    (import ../../scripts/rebuild.nix { inherit pkgs; })
  ];
}
